title: 北美世界记述
description: "一个记述北美事情的网站"
author:
  name: "skyView"
  email: "support@naworld.et"
  url: "https://blog.naworld.net"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "SomeHacker"
year : "2024"
